### ISSUE TITLE
Configuration for specific ajax sensor 

### ISSUE THREAD

**Issue by olylak** [eavanvalkenburg/sia#12]
Is it possible to get a configuration example of how to add/list a specific ajax devices under a zone section like DoorProtect or MotionProtect, etc.?

Could you also clarify if it is possible to track a state (on/off) of Ajax Wallswitch, Relay or Socket ? Is it possible to turn it on of off from home assistant?

Thanks in advance!

**Comment by eavanvalkenburg** [comment]
Hi, that kind of level of detail is not available through SIA. I'm looking into if turning the alarm on and off is supported.
