### ISSUE TITLE
State after tiggered alarm

### ISSUE THREAD

**Issue by goots86** [eavanvalkenburg/sia#13]
Hello,

I try to implement Sia/Ajax with HA but I have some problem.

When hub send a triggered alarm to HA, after end of alarm, HA reset state of alarm on disarmed ?

It's a normal working of script ? or it's a bug ?

Thanks for your answer.

My HA run on docker for your information.
HA version : 0.108.9

**Comment by goots86** [comment]
I find something :
In file __init__.py line 170 : "BR": {"type": DEVICE_CLASS_ALARM, "new_state": STATE_ALARM_DISARMED},

BR in SIA event xls means : Alarm/trouble condition has been eliminated and not DISARMED.

**Comment by eavanvalkenburg** [comment]
That is a good catch, I will look into it, thanks!

**Comment by eavanvalkenburg** [comment]
@goots86 just to check, the expectation is that the alarm goes back to the state it had previously, either Night or Away, correct?

**Comment by goots86** [comment]
Yes, but in fact, the state goes to disarmed.

**Comment by eavanvalkenburg** [comment]
This was fixed in the v0.3.2 release.
