### ISSUE TITLE
AlarmControlPanel is deprecated

### ISSUE THREAD

**Issue by jyourstone** [eavanvalkenburg/sia#15]
I'm using Home Assistant 0.110.5 and I can't get the alarm control panel to work. I get these error messages in the logs:

Logger: homeassistant.components.alarm_control_panel
Source: components/alarm_control_panel/__init__.py:194
Integration: Alarm control panel (documentation, issues)
First occurred: 5:19:28 PM (1 occurrences)
Last logged: 5:19:28 PM

AlarmControlPanel is deprecated, modify SIAAlarmControlPanel to extend AlarmControlPanelEntity

**Comment by conrad66** [comment]
I have the same error

**Comment by eavanvalkenburg** [comment]
please move to the beta, by doing "reinstall" and then selecting v0.3.2b
