### ISSUE TITLE
[Question] How to setup 2 leak sensors?

### ISSUE THREAD

**Issue by Mokson** [eavanvalkenburg/sia#29]
Could you please advise how to configure 2 leak sensors, so they would be recognized as 2 different entities in HA?

Currently, both of them are reported to a single entity in HA (I can tell this by imitating a leak, and a single entry in HA will reflect state of both)

**Comment by eavanvalkenburg** [comment]
Unless there in two different zones, the SIA protocol does not distinguish between them.

**Comment by Mokson** [comment]
Could you please help to understand how to 'create' zones? )

**Comment by eavanvalkenburg** [comment]
I'm not sure, I don't use them.
