### ISSUE TITLE
Alarmstate doesn't change when using alarmschedule to activate nightmode

### ISSUE THREAD

**Issue by stiq78** [eavanvalkenburg/sia#31]
I have created an alarmschedule in my Ajax hub to activate nightmode at night and deactivate it in the morning.
My problem is that the the SIA component doesn't react for the "activate nightmode" event. 
If I activate nightmode manually the schedule deactivates it in the morning and this event is picked up by the SIA component.
Also if the schedule activates full armed mode, the event is picked by SIA.

So the only problem is when the schedule activates nightmode.

Maybe the problem is within the hub and not the SIA component at all.
An maybe I can add some debug prints somewhere to collect some more information about this?

//Stefan

**Comment by eavanvalkenburg** [comment]
The SIA protocol doesn't allow changing the alarmstate, so this will not be fixed.

**Comment by stiq78** [comment]
Hi!
I think we missunderstood each other.
The schedule is configured by the Ajax-app and stored in the Ajax hub. So the activation/deactivation is done by the hub itself, not in Homeassistant.

The problem is that HA+SIA component didn't pick up the activate nightmode event, when nightmode is triggered from an Ajax alarmschedule. 

I think I should write an issue about this on Ajax support forum also,  but I thought I could maybe do some more logging in HA to be sure who's fault it is.

**Comment by eavanvalkenburg** [comment]
ah sorry, what you can then do is turn on logging, judging from the docs, it seems that gives the NC code, so you can add that one in the same way as NL looks, in your HA folder into file const.py. Let me know if that does the trick!

**Comment by stiq78** [comment]
Cool, it worked! 
I added NC code just like the NL code to const.py and restarted HA.
Thank you!
