### ISSUE TITLE
Alarm status unavailable after wrong keycode entry

### ISSUE THREAD

**Issue by dogghy14** [eavanvalkenburg/sia#34]
Hi, 

after making a mistake in entering the code from the physical keypad, the SIA integration has stopped working.

In the logs I find this message:
2020-11-18 10:19:40 WARNING (MainThread) [pysiaalarm.base_sia_server] Code not found, replying with DUH to account: AC3

Could you please help me to fix this situation?

Tz,
Andrea

**Comment by eavanvalkenburg** [comment]
There should be a message with the actual code before this log message, this one basically says, SIA wide, this is a unknown code (has nothing to do with HA), so I will tell the alarm that I don't know what to do with it, which is the DUH message. So I would need to know the code itself, so that I can add that, in this file of the underlying packages, all known codes are listed, this is what is used to check against: https://github.com/eavanvalkenburg/pysiaalarm/blob/master/src/pysiaalarm/sia_const.py

**Comment by eavanvalkenburg** [comment]
And it shouldn't stop the SIA integration to stop working, but it might do something with the alarm itself.

**Comment by dogghy14** [comment]
The only logs in home-assistant.log file are:

```
config $ grep sia home-assistant.log
2020-11-18 16:49:32 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for sia which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-11-18 16:51:17 WARNING (MainThread) [pysiaalarm.base_sia_server] Code not found, replying with DUH to account: AC3

```

Are there any other logs I can look at?


Andrea

**Comment by dogghy14** [comment]
Here's to you: 

`2020-11-18 17:05:58 DEBUG (MainThread) [pysiaalarm.base_sia_server] Parsed event: Content: IjOJ5u7|#AC3|Nri2/JC2]_16:06:10,11-18-2020, Zone: 2, Code: JC, Message: 2, Concerns: None, Type: None, Description: None, Account: AC3, Receiver: None, Prefix: L0, Timestamp: 2020-11-18 16:06:10, Length: 0075, Sequence: 5732, CRC: BFA6, Calc CRC: BFA6, Message type: None, Encrypted Content: 48D708D3DECD94A6A5605193C63542B11BACC02C33F982028A877D2621E47AE03B7408B3FD62D6386484C1CE99D996F6, Full Message: "*SIA-DCS"5732L0#AC3[48D708D3DECD94A6A5605193C63542B11BACC02C33F982028A877D2621E47AE03B7408B3FD62D6386484C1CE99D996F6..
20`


Thanks,
Andrea

**Comment by eavanvalkenburg** [comment]
So indeed the JC code is not in the package, which type of alarm are you using?

**Comment by dogghy14** [comment]
I'm using an Ajax System alarm. The central unit is Hub Plus

**Comment by dogghy14** [comment]
I found this, maybe it can help: [http://86.49.187.98/Ajax/CID%20a%20SIA/Ajax_SIA_CID_Codes.xlsx](url)

**Comment by eavanvalkenburg** [comment]
Yeah, the problem is that Ajax occasionally adds codes that are not in the regular SIA spec, so I'll do an update of those in the package next week.

**Comment by dogghy14** [comment]
Super! Many thanks

**Comment by dogghy14** [comment]
Hi Eduard, 

when will the next version be released?


Thank you
