### ISSUE TITLE
Scene

### ISSUE THREAD

**Issue by suburweb** [eavanvalkenburg/sia#36]
When the system is armed through a scene, it does not send the armed status to homeassistant

**Comment by eavanvalkenburg** [comment]
What kind of scene are you referring to?

**Comment by suburweb** [comment]
I activate a scene at an hour so that it is armed at home and does not report the status to the home assistant . Disarmed en home assistant

**Comment by eavanvalkenburg** [comment]
but are you referring to Scenes in Home Assistant in scenes in your alarm? This sia protocol does not allow you to set the alarm, so you cannot arm/disarm the alarm through HA.

**Comment by utester123123bb** [comment]
same issue. status is updating only manually and not using through the scenes (automations) in ajax app (automations run in Ajax Hub and trigger this actions)

**Comment by utester123123bb** [comment]
I mean that when I set arming manually - this status will be updated in HA, but when we set arming by scene (example: set arming in 23:00 - it's not work, strange but the same automation with disarming works as expected)

**Comment by eavanvalkenburg** [comment]
Could you both then turn on logging in ha and report back which messages are sent by ajax to ha, and also update to the beta in HACS because I think I've added some extra codes there already!

**Comment by utester123123bb** [comment]
> Could you both then turn on logging in ha and report back which messages are sent by ajax to ha, and also update to the beta in HACS because I think I've added some extra codes there already!

Ok will try to updated plugin!

**Comment by suburweb** [comment]
Forgive my clumsiness
How do I update the beta version from Hacs?

**Comment by eavanvalkenburg** [comment]
I think under `update information` for the integration in the HACS interface, but I'm not behind my computer now...

**Comment by suburweb** [comment]
Thank you. I have installed version v0.3.11-beta.2 and will test the scene

**Comment by suburweb** [comment]
The scene I have tested with this version and it works fine. Thank you

**Comment by eavanvalkenburg** [comment]
That is fantastic to hear! What about you @vitaliy-kozlov ?
