### ISSUE TITLE
Last Heartbeat - Alarm status is not displayed in Homekit using Homekit Bridge.

### ISSUE THREAD

**Issue by vitaliy-kozlov** [eavanvalkenburg/sia#39]
Last Heartbeat - not added to Homekit using Homekit bridge.
Hi, First of all many thanks for your exceptional work! This plugin is really awesome but is there any solution to add Last Heartbeat sensor to Homekit? maybe as occupancy motion sensor? Homekit Bridge export only leak/gas and security status to homekit. Last Heartbeat is not displayed. Maybe there are something wrong with sensor settings or something wrong from the homekit side?

**Comment by eavanvalkenburg** [comment]
not sure what happens with that, but someone just added a power sensor (binary) to this integration, so you might be able to leverage that, warning: it has state unknown until the power actually goes off (and it falls back to battery), check it out!

**Comment by vitaliy-kozlov** [comment]
Fixed. Please close the issue. Thanks
