### ISSUE TITLE
HACS keeps proposing v3.11 even if v4.0-beta2 is installed

### ISSUE THREAD

**Issue by BaQs** [eavanvalkenburg/sia#44]
## Configuration

```yaml

Add your configuration here.

```

## Describe the bug

HACS keeps proposing v3.11 even if v4.0-beta2 is installed.
Probably a new release tag is missing ?

## Debug log

```text

Add your logs here.

```

**Comment by eavanvalkenburg** [comment]
this was due to the fact I updated v4 with the version tag in the manifest before v3, which caused HACS to thing the v3 was newer, fixed now with new beta's
