### ISSUE TITLE
Error when trying to configure SIA

### ISSUE THREAD

**Issue by rvrignaud** [eavanvalkenburg/sia#45]
## Version of the custom_component and HA setup (version, OS, etc)
I'm running HA core-2021.4.6
OS : Raspbian 10
SIA on branch from latest beta commit bbe80ec

## Configuration
Trying to setup SIA integration. Only changing port to 8124 and Account to "AAA" as in example.

## Describe the bug
Form is reseting and displaying "Unexpected error"

## Debug log
```text
May 08 09:38:12 pi hass[15841]: 2021-05-08 09:38:12 ERROR (MainThread) [custom_components.sia.config_flow] Unexpected exception
May 08 09:38:12 pi hass[15841]: Traceback (most recent call last):
May 08 09:38:12 pi hass[15841]:   File "/home/homeassistant/.homeassistant/custom_components/sia/config_flow.py", line 108, in async_step_user
May 08 09:38:12 pi hass[15841]:     await self.async_set_unique_id(f"{DOMAIN}_{self.data[CONF_PORT]}")
May 08 09:38:12 pi hass[15841]: TypeError: 'NoneType' object is not subscriptable

```

**Comment by shinyone** [comment]
Yes, same for me  v0.5.0-beta.5

**Comment by eavanvalkenburg** [comment]
I'll have a look

**Comment by eavanvalkenburg** [comment]
Just published new release, check it and let me know!

**Comment by rvrignaud** [comment]
5845a53 fixed my problem.
Closing this one.
Thank you
