### ISSUE TITLE
Filtering device - Ajax

### ISSUE THREAD

**Issue by Drealine** [eavanvalkenburg/sia#50]
Hi,

Just an issue to tell you that Teams Ajax told me that SIA send also the number of the device in the SIA packet.

This is the email : 

```
Dear client,
 
When you receive a notification about, for example, opening/closing a door, the SIA line should also indicate the group number and the number of the device that generated the event.

```
![tt](https://user-images.githubusercontent.com/61891683/132942999-c16770f8-e227-4d00-9ef4-ce4e477e5ad5.png)

When I listen SIA event in nodred, I see that it seems the content **message** but indicate 502 for example with 2 which is the device number (I tested with devices and it's the only number that change: 

![image](https://user-images.githubusercontent.com/61891683/132943035-25c64df9-1c4b-4419-9904-789fb8d541ea.png)

**Comment by eavanvalkenburg** [comment]
This might work, but in the SIA protocol the message can be used in any way the manufacturer wants, so Ajax might do it this way, but some other company uses it differently and I don't want to support that, I noticed you already have a template sensor running off of that which is fantastic and the exact reason I create the event stream as well, for future reference see here: https://community.home-assistant.io/t/ajax-alarm-system/62853/387?u=eavanvalkenburg
