### ISSUE TITLE
access device registry

### ISSUE THREAD

**Issue by floow77** [eavanvalkenburg/sia#53]
## Configuration

```yaml

Home Assistant Core 2022.6.1
Home Assistant Supervisor 2022.05.3
Home Assistant OS 8.1


SIA v1.0.0-beta1

```

## Describe the bug
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:103
First occurred: 16:41:28 (2 occurrences)
Last logged: 16:41:34

Detected integration that uses deprecated `async_get_registry` to access device registry, use async_get instead. Please report issue to the custom component author for sia using this method at custom_components/sia/hub.py, line 59: device_registry = await dr.async_get_registry(self._hass)

## Debug log

```text

Add your logs here.

```

**Comment by eavanvalkenburg** [comment]
Please switch to the official integration, I haven't done any work on this one so it is no longer up to date!

**Comment by eavanvalkenburg** [comment]
See the top of the readme:

OFFICIAL INTEGRATION IS NOW IN HA!
Make sure to delete the current integraiton, in your Integrations page, then delete the HACS custom component, reboot and then input your config in the official integration config. There are some settings, most importantly ignoring timestamps, in a options flow (press configure after installing the integration).
