### ISSUE TITLE
last state

### ISSUE THREAD

**Issue by conrad66** [eavanvalkenburg/sia#8]
After reboot home assistant, the alarm_control_panel state is always disarmed.
How to restore the real state ?

**Comment by eavanvalkenburg** [comment]
hi, there is a way to do that, but I haven't gotten around to implementing it, I'll put it on my list, thanks for the reminder.

**Comment by conrad66** [comment]
Thanks!
We'll wait.
Hopefully, States of other sensors will also recover after reboot HA.

**Comment by conrad66** [comment]
I accidentally closed this Issues
