### ISSUE TITLE
Entity id already exists: sensor.ajax_last_heartbeat - No dynamically added sensors

### ISSUE THREAD

**Issue by Tuschz** [eavanvalkenburg/sia#9]
## Configuration

```yaml

Add your configuration here.
sia:
  port: 1241
  hubs:
    - name: Ajax
      account: AAA
```

## Describe the bug
Issue when adding first time setup.

Can only get the sensor for heartbeat, no other devices or sensors are added dynamically as stated in the readme

## Debug log

2019-12-04 23:22:09 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.sia
2019-12-04 23:22:09 DEBUG (MainThread) [custom_components.sia.sensor] SIASensor: setup: devices: [<Entity Ajax Last heartbeat: 2019-12-04T23:22:08.412404+00:00>]
2019-12-04 23:22:09 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 399, in _async_add_entity
    raise HomeAssistantError(msg)
homeassistant.exceptions.HomeAssistantError: Entity id already exists: sensor.ajax_last_heartbeat

**Comment by Tuschz** [comment]
So it is trying to create a sensor that is already there. in this part

async def async_setup_platform(hass, config, async_add_entities, discovery_info=None):
    """Implementation of platform setup from HA."""
    devices = [
        device
        for hub in hass.data[DOMAIN].values()
        for device in hub._states.values()
        if isinstance(device, SIASensor)
    ]
    _LOGGER.debug("SIASensor: setup: devices: " + str(devices))
    async_add_entities(devices)


Perhaps incorporate 
   def get(self, entity_id: str) -> Optional[State]:
        """Retrieve state of entity_id or None if not found.
        Async friendly.
        """
        return self._states.get(entity_id.lower())

**Comment by olylak** [comment]
Having the same issue. Any updates on that?

**Comment by eavanvalkenburg** [comment]
Hi @olylak and @Tuschz, I have the same myself but haven't had time to address it, hopefully I'll have some time this week to tackle this!

**Comment by MrGMan133** [comment]
I have the same problem, tried changing the name, however, that did not resolve the issue. Also downgraded to V0.2.2 did not solve it. Home assistant does give a response to sensor.ajax_last_heartbeat, however the alarm_control_panel does not show up.

**Comment by eavanvalkenburg** [comment]
With the setup above, you would not see sensors until a message is sent from your alarm system to HA, I'll dubblecheck that behaviour to make sure.

**Comment by eavanvalkenburg** [comment]
@MrGMan133 I checked and for me adding the alarm control panel dynamically works, so with a setup without zones and sensors, after the first change of state (arming the alarm and then disarming it does show up, but I did notice that the behaviour around the sensor name was different, which I can't really figure out the reason for, for me the dynamically added one was different and I had to go into the states page in developer tools to see it. I don't have moisture and smoke sensors so can't test those.
